# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20)),
                ('cat_picture', models.ImageField(blank=True, null=True, upload_to='cat_images')),
                ('story', models.CharField(max_length=140)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_app.UserProfileInfo')),
            ],
        ),
    ]
