# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_app', '0003_cat_topic_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_topic_comment',
            name='comment_picture',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images'),
        ),
    ]
