# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_app', '0004_cat_topic_comment_comment_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_topic_comment',
            name='comment_picture',
        ),
        migrations.AddField(
            model_name='cat_topic_comment',
            name='comment_picture_path',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
